services:
  - type: web
    name: node-crud-app
    env: node
    plan: free   # or starter, standard depending on your needs
    buildCommand: "npm install --legacy-peer-deps"
    startCommand: "cd src && node index.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
